
import type { IconName } from '@/components/icons';
export type Language = 'en' | 'es';

interface SocialLinkItem {
  name: string;
  url: string;
  iconName: IconName;
  ariaLabel: string;
}

interface Donor {
  name: string;
  amount: string;
  message: string;
}

export const content: Record<Language, any> = {
  en: {
    common: {
      changeLanguage: "Change language",
      languageMenu: {
          english: "English",
          spanish: "Spanish",
      },
      appName: "PredictPal",
      learnMore: "Learn More",
      getStarted: "Get Started",
    },
    nav: {
      home: "Home",
      mundialDeClubes: "FIFA Club World Cup",
      academy: "Academy",
      donations: "Donations", 
    },
    hero: {
      title: 'A "Bet"ter Way to Wager',
      subtitle: "PredictPal uses advanced neural networks to offer you match forecasts and betting strategies with unparalleled accuracy. Stop betting blind and start making data-driven decisions.",
      ctaPrimary: "View FIFA Club World Cup",
      ctaSecondary: "Explore the Academy",
    },
    problem: {
      title: "Tired of Losing Due to Lack of Reliable Information?",
      description: "In the world of table tennis betting, the lack of accurate analysis and reliable data leads to financial losses and growing distrust in betting strategies. Existing models are often inconsistent and do not offer the depth needed to make informed decisions.",
    },
    solution: {
      title: "Your Ultimate Solution for Smart Table Tennis Betting",
      description: "PredictPal offers you exclusive access through our web platform to advanced predictive analysis and personalized strategies. Our neural network technology is specifically designed for table tennis, ensuring highly reliable forecasts so you can maximize your profits and bet with confidence.",
      features: [
        {
          title: "Accurate Forecasts",
          description: "Access match predictions generated by advanced neural networks.",
          icon: "Target",
        },
        {
          title: "Detailed Analysis",
          description: "Receive in-depth statistics and analysis for each match.",
          icon: "BarChart3",
        },
        {
          title: "Personalized Strategies",
          description: "Develop your own betting strategies with our tools and data.",
          icon: "Settings2",
        },
        {
          title: "Continuous Education",
          description: "We offer courses and tips for you to become a professional and responsible bettor.",
          icon: "GraduationCap",
        },
      ],
    },
    targetAudience: {
      title: "An Essential Tool for...",
      profiles: [
        {
          name: "Professional and Amateur Bettors",
          description: "Radically improve your decisions and results in table tennis betting.",
          icon: "Users",
        },
        {
          name: "Betting Houses",
          description: "Enrich your product offerings with high-quality data and predictions.",
          icon: "Building",
        },
        {
          name: "Analysts and Sports Journalists",
          description: "Access accurate data and reliable forecasts for your content.",
          icon: "Newspaper",
        },
      ],
    },
    milestones: {
      title: "Our Journey and Next Steps",
      achieved: {
        title: "Milestones Achieved:",
        items: [
          "Development of 5 predictive neural networks.",
          "Implementation of the web platform with FastAPI backend and Next.js frontend.",
          "User authentication system for access to premium features.",
        ],
        icon: "Goal"
      },
      vision: {
        title: "Our Vision:",
        items: [
          "Reach 10,000 premium subscribers in our first year.",
          "Establish strategic alliances with at least 3 betting houses.",
          "Expand our predictive capabilities to revolutionize the analysis of other 1v1 sports.",
        ],
        icon: "Rocket"
      },
    },
    pricing: {
      title: "Choose the Perfect Plan for You",
      plans: [
        {
          name: "Premium Subscriptions",
          description: "Unlimited access to all our detailed analyses and exclusive predictions.",
          icon: "Gem",
        },
        {
          name: "Personalized Consulting",
          description: "Advisory services for professional bettors seeking a competitive edge.",
          icon: "UserCheck",
        },
        {
          name: "Courses and Training",
          description: "Learn data analysis and betting strategies from experts.",
          icon: "BookOpen",
        },
      ],
    },
    donationsPage: { 
      metaTitle: "Donate to PredictPal | Support Our Project",
      metaDescription: "Support PredictPal by making a donation. Help us improve our table tennis prediction platform and community resources.",
    },
    donations: {
      sectionId: "donations-content",
      title: "Help Us Build the Future of PredictPal",
      introduction: "PredictPal is more than just a tool; it's a community built for and by table tennis lovers. To keep growing and delivering the best features, your support is essential.",
      listTitle: "Your donation is directly invested in the platform's future. It helps us to:",
      listItems: [
        {
          title: "Dedicate more time",
          description: "It allows me to focus on improving and expanding PredictPal."
        },
        {
          title: "Accelerate development",
          description: "Release the features we all want to see, much faster!"
        },
        {
          title: "Build a team",
          description: "It brings us closer to the goal of hiring more talent to take the website to the next level."
        }
      ],
      callout: {
        title: "Leave your mark!",
        description: "When you donate, you can include a message of support. I will personally add it to our website to thank those who make this project possible."
      },
      conclusion: "With your help, we're not just maintaining the platform; we're transforming it. Be a part of our growth and help us build the future of table tennis analytics!",
      paypalButtonText: "Donate with PayPal",
      paypalButtonAriaLabel: "Donate with PayPal to support PredictPal",
      thanksTitle: "Special Thanks To Our Donors",
      donors: [
        { name: "MasTho0128", amount: "$50", message: "Hope this is a good initial boost for you guys =D" },
      ] as Donor[],
    },
    footer: {
      copyright: `© ${new Date().getFullYear()} PredictPal. All rights reserved.`,
      message: "Bet responsibly.",
      socialLinks: [
        { name: "X", url: "https://x.com/predictpal", iconName: "Twitter", ariaLabel: "Follow us on X" },
        { name: "Instagram", url: "https://instagram.com/predictpal", iconName: "Instagram", ariaLabel: "Follow us on Instagram" },
        { name: "TikTok", url: "https://tiktok.com/@predictpal", iconName: "Music", ariaLabel: "Follow us on TikTok" },
        { name: "Youtube", url: "https://youtube.com/@predictpal", iconName: "Youtube", ariaLabel: "Follow us on Youtube" },
      ] as SocialLinkItem[],
    },
  },
  es: {
    common: {
      changeLanguage: "Cambiar idioma",
      languageMenu: {
          english: "Inglés",
          spanish: "Español",
      },
      appName: "PredictPal",
      learnMore: "Aprende Más",
      getStarted: "Comenzar",
    },
    nav: {
      home: "Inicio",
      mundialDeClubes: "Mundial de Clubes FIFA",
      academy: "Academia",
      donations: "Donaciones", 
    },
    hero: {
      title: "El futuro de tu apuesta, decidido en tiempo presente.",
      subtitle: "PredictPal utiliza redes neuronales avanzadas para ofrecerte pronósticos de partidos y estrategias de apuestas con una precisión inigualable. Deja de apostar a ciegas y empieza a tomar decisiones basadas en datos.",
      ctaPrimary: "Ver Mundial de Clubes FIFA",
      ctaSecondary: "Explorar la Academia",
    },
    problem: {
      title: "¿Cansado de Perder por Falta de Información Fiable?",
      description: "En el mundo de las apuestas de tenis de mesa, la falta de análisis precisos y datos confiables conduce a pérdidas financieras y a una desconfianza creciente en las estrategias de apuestas. Los modelos existentes a menudo son inconsistentes y no ofrecen la profundidad necesaria para tomar decisiones informadas.",
    },
    solution: {
      title: "Tu Solución Definitiva para Apuestas Inteligentes en Tenis de Mesa",
      description: "PredictPal te ofrece acceso exclusivo a través de nuestra plataforma web a análisis predictivos avanzados y estrategias personalizadas. Nuestra tecnología de redes neuronales está específicamente diseñada para el tenis de mesa, garantizando pronósticos altamente fiables para que maximices tus ganancias y apuestes con confianza.",
      features: [
        {
          title: "Pronósticos Precisos",
          description: "Accede a predicciones de partidos generadas por redes neuronales avanzadas.",
          icon: "Target",
        },
        {
          title: "Análisis Detallado",
          description: "Recibe estadísticas y análisis profundos para cada encuentro.",
          icon: "BarChart3",
        },
        {
          title: "Estrategias Personalizadas",
          description: "Desarrolla tus propias estrategias de apuestas con nuestras herramientas y datos.",
          icon: "Settings2",
        },
        {
          title: "Educación Continua",
          description: "Ofrecemos cursos y consejos para que te conviertas en un apostador profesional y responsable.",
          icon: "GraduationCap",
        },
      ],
    },
    targetAudience: {
      title: "Una Herramienta Esencial para...",
      profiles: [
        {
          name: "Apostadores Profesionales y Aficionados",
          description: "Mejora radicalmente tus decisiones y resultados en las apuestas de tenis de mesa.",
          icon: "Users",
        },
        {
          name: "Casas de Apuestas",
          description: "Enriquece tu oferta de productos con datos y predicciones de alta calidad.",
          icon: "Building",
        },
        {
          name: "Analistas y Periodistas Deportivos",
          description: "Accede a datos precisos y pronósticos fiables para tus contenidos.",
          icon: "Newspaper",
        },
      ],
    },
    milestones: {
      title: "Nuestro Camino y Próximos Pasos",
      achieved: {
        title: "Hitos Alcanzados:",
        items: [
          "Desarrollo de 5 redes neuronales predictivas.",
          "Implementación de la plataforma web con backend en FastAPI y frontend en Next.js.",
          "Sistema de autenticación de usuarios para acceso a funciones premium.",
        ],
        icon: "Goal"
      },
      vision: {
        title: "Nuestra Visión:",
        items: [
          "Alcanzar los 10,000 suscriptores premium en nuestro primer año.",
          "Establecer alianzas estratégicas con al menos 3 casas de apuestas.",
          "Expandir nuestras capacidades predictivas para revolucionar el análisis de otros deportes 1 vs 1.",
        ],
        icon: "Rocket"
      },
    },
    pricing: {
      title: "Elige el Plan Perfecto para Ti",
      plans: [
        {
          name: "Suscripciones Premium",
          description: "Acceso ilimitado a todos nuestros análisis detallados y predicciones exclusivas.",
          icon: "Gem",
        },
        {
          name: "Consultoría Personalizada",
          description: "Servicios de asesoramiento para apostadores profesionales que buscan una ventaja competitiva.",
          icon: "UserCheck",
        },
        {
          name: "Cursos y Formación",
          description: "Aprende análisis de datos y estrategias de apuestas de la mano de expertos.",
          icon: "BookOpen",
        },
      ],
    },
    donationsPage: { 
      metaTitle: "Dona a PredictPal | Apoya Nuestro Proyecto",
      metaDescription: "Apoya a PredictPal haciendo una donación. Ayúdanos a mejorar nuestra plataforma de predicción de tenis de mesa y recursos comunitarios.",
    },
    donations: {
      sectionId: "donations-content",
      title: "Ayúdanos a construir el futuro de PredictPal",
      introduction: "PredictPal es más que una herramienta; es una comunidad construida para y por amantes del tenis de mesa. Para seguir creciendo y ofreciendo las mejores funcionalidades, tu apoyo es fundamental.",
      listTitle: "Tu donación se invierte directamente en el futuro de la plataforma. Nos ayuda a:",
      listItems: [
        {
          title: "Dedicar más tiempo",
          description: "Me permite enfocarme en mejorar y expandir PredictPal."
        },
        {
          title: "Acelerar el desarrollo",
          description: "Lanzar las mejoras que todos queremos ver, ¡mucho más rápido!"
        },
        {
          title: "Construir un equipo",
          description: "Nos acerca al objetivo de sumar más talento para llevar la web al siguiente nivel."
        }
      ],
      callout: {
        title: "¡Deja tu huella!",
        description: "Al donar, puedes incluir un mensaje de apoyo. Lo añadiré personalmente a nuestra web como agradecimiento a quienes hacen posible este proyecto."
      },
      conclusion: "Con tu ayuda, no solo mantenemos la plataforma, sino que la transformamos. ¡Sé parte de nuestro crecimiento y ayúdanos a construir el futuro del análisis del tenis de mesa!",
      paypalButtonText: "Donar con PayPal",
      paypalButtonAriaLabel: "Donar con PayPal para apoyar a PredictPal",
      thanksTitle: "Agradecimientos Especiales a Nuestros Donantes",
      donors: [
        { name: "MasTho0128", amount: "$50", message: "Espero que esto sea un buen impulso inicial para ustedes, chicos =D" },
      ] as Donor[],
    },
    footer: {
      copyright: `© ${new Date().getFullYear()} PredictPal. Todos los derechos reservados.`,
      message: "Apuesta con responsabilidad.",
      socialLinks: [
        { name: "X", url: "https://x.com/predictpal", iconName: "Twitter", ariaLabel: "Síguenos en X" },
        { name: "Instagram", url: "https://instagram.com/predictpal", iconName: "Instagram", ariaLabel: "Síguenos en Instagram" },
        { name: "TikTok", url: "https://tiktok.com/@predictpal", iconName: "Music", ariaLabel: "Síguenos en TikTok" },
        { name: "Youtube", url: "https://youtube.com/@predictpal", iconName: "Youtube", ariaLabel: "Síguenos en Youtube" },
      ] as SocialLinkItem[],
    },
  },
};
